### ISSUE TITLE
SASS nesting is not working "Illegal nesting: Only properties may be nested beneath properties."

### ISSUE THREAD

**Issue by sems** [semspanhaak/sems.dev#7]
The SASS nesting is giving an error wish in my opinion is not right. 
`=> changed: /Users/user/projects/semspanhaak.nl/home-app/src/styles/portfolio.sass
{
  "status": 1,
  "file": "/Users/user/projects/semspanhaak.nl/home-app/src/styles/portfolio.sass",
  "line": 70,
  "column": 9,
  "message": "Illegal nesting: Only properties may be nested beneath properties.",
  "formatted": "Error: Illegal nesting: Only properties may be nested beneath properties.\n        on line 70 of src/styles/portfolio.sass\n>>         .case_link {\n\n   --------^\n"
}`

when is nested like this:
![image](https://user-images.githubusercontent.com/11527464/41086640-edc10d00-6a3a-11e8-97fa-319a7f9723b9.png)

**Comment by sems** [comment]
### Possible solution 
In my case it was 'whitespacing'. SASS doesn't say it was the problem. But after going trough some steps I found out the new code was added with spaces. While the code it is nested in is written with tab. 

For anyone out there having this problem you can turn whitespaces on by going into your editor settings/preferences and turn them on. In case of VsCode just at the following line to the `USER SETTINGS` file `"editor.renderWhitespace": "all", `

### Images
From this: 
![image](https://user-images.githubusercontent.com/11527464/41089510-42227594-6a42-11e8-9fc2-10d9e9aad564.png)

To this: 
![image](https://user-images.githubusercontent.com/11527464/41089516-4ad22ab8-6a42-11e8-9e83-2d77f6022a2e.png)

**Comment by jmaczan** [comment]
Thx @semspanhaak, did you create issue for this in Sass? The communicate is veeery misleading

**Comment by sems** [comment]
> Thx @semspanhaak, did you create issue for this in Sass? The communicate is veeery misleading

Nope I did not create the issue over this, mainly because it's a fault of the user and not 
Sass itself :D
